name: Open Land Music
favicon: null
layout_spectrum: 0.7295269777532667
typography_spectrum: 0.6488552715163678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6300834387075156
  lightness: 0.6542582160327584
  saturation: 0.3060016317758709
  rhythmicContrast: 0.7159612171817571
purpose: []
